site_name: "LOSS's Notebook"
site_url: https://mydomain.org/mysite


edit_uri: https://github.com/LLLOSS/loss/tree/main/docs # 编辑按钮跳转的链接
repo_url: https://github.com/LLLOSS/loss # 右上角点击跳转的链接
repo_name: LOSS.github # 右上角的名字
copyright: Copyright &copy; 2025~ LOSS_zjh Rights Reserved. # 左下角的版权声明

theme:
  name: material
  language: zh
  favicon: images/heidashuai_yuan.png"
  icon:
    # logo: material/pac-man
    logo: octicons/paper-airplane-16
    repo: fontawesome/brands/github-alt
    admonition:
      info: fontawesome/solid/anchor
      note: fontawesome/solid/pen-nib
      abstract: fontawesome/solid/list
      tip: fontawesome/solid/lightbulb
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: material/alien
      danger: fontawesome/solid/virus
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/link
  font:
    text: LXGW WenKai Screen GB Screen # Share Tech
    code: JetBrains Mono
  palette:
    scheme: default
    primary: brown
    accent: deep orange
  features:
    - content.code.annotate
    - content.code.copy
    # - navigation.instant # This will cause LaTeX render fail at the first try.
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    # - navigation.prune
  #custom_dir: overrides

plugins:
  - minify
  # - statistics:
  #     words_per_minute: 200
  - glightbox
  - search:
      lang:
        - zh
        - en
      separator: '[\s\-\.]+'
  # - git-revision-date-localized:
  #     type: datetime
  #     timezone: Asia/Shanghai
  #     locale: zh
  #     enable_creation_date: true
  #     exclude:
  #       - index.md
  #       - coming.md
  #       - link.md
  #       - tech_accu/index.md
  #       - cour_note/index.md
  #       - pape_read/index.md
  #       - others/index.md
markdown_extensions:
  - toc:
      permalink: true # link for each title
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}} # enable Unicode link
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      # smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  # - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.tilde
  #- mdx_math
  - tables
  - md_in_html
#KaTeX cdn from: [ https://www.bootcdn.cn/KaTeX/ ]

extra_css:
  #- _css/extra.css
  - _css/flink.css
  - _css/counter.css
  - _css/custom.css
  - _css/tasklist.css
  - _css/card.css
  #- _css/changelog_extra.css
  # - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css
  # - https://cdn.jsdelivr.net/npm/cn-fontsource-lxgw-wen-kai-gb-screen@1.0.6/font.min.css
  ###- https://jsd.cdn.zzko.cn/npm/katex@0.16.4/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  #- https://cdn.staticfile.org/lxgw-wenkai-screen-webfont/1.6.0/lxgwwenkaiscreen.css

extra_javascript:
  - _js/extra.js
#  - _js/mathjax.js
  - _js/katex.js
  #- https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.js
  ###- https://jsd.cdn.zzko.cn/npm/katex@0.16.4/dist/katex.min.js
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#####
# #  - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/javascripts/extra.js  # extra的cdn
#   - javascripts/mathjax.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# # #####
nav:
  - Home: 
    - index.md
  - 学研札记:
    - CourseNotes/index.md
    - 模电:
      - CourseNotes/analogue/11电阻失配对 CMRR 的影响分析及仿真验证.md
      - CourseNotes/analogue/10五管OTA的输入等效失调电压优化.md
      - MOSFET噪声特性的标定与五管OTA的噪声优化: CourseNotes/analogue/9MOSFET噪声特性的标定与五管OTA的噪声优化.md
      - CourseNotes/analogue/8密勒运算放大器的系统性设计.md
      - CourseNotes/analogue/7反馈系统的稳定性分析与优化设计.md
      - CourseNotes/analogue/6共源共栅电流镜的设计.md
      - CourseNotes/analogue/5单极NMOS共源极放大器的设计.md
      - CourseNotes/analogue/4MOSFET的弱反型区.md
      - CourseNotes/analogue/3频率响应.md
      - CourseNotes/analogue/2五管OTA的设计.md
      - CourseNotes/analogue/1共射放大器的设计.md
    - 微电子器件物理:
      - CourseNotes/index.md
    - 电路分析:
      - CourseNotes/index.md
    - 量子力学:
      - CourseNotes/quantum/函数空间与向量空间对比.md
      - CourseNotes/quantum/波函数、Dirac表示与矩阵表示的对比.md
  - 知行笺:
    - The first day: Reflections/The First Echo of LOSS.md
  #- 标签: tag.md
