site_name: "Echoes of LOSS"
site_url: https://mydomain.org/mysite


edit_uri: https://github.com/LLLOSS/loss/tree/main/docs # 编辑按钮跳转的链接
repo_url: https://github.com/LLLOSS/loss # 右上角点击跳转的链接
repo_name: LOSS.github # 右上角的名字

theme:
  name: material
  language: zh
  favicon: _assets/iro/IroPatch_Brown.ico
  icon:
    # logo: material/pac-man
    logo: octicons/paper-airplane-16
    repo: fontawesome/brands/github-alt
    admonition:
      info: fontawesome/solid/anchor
      note: fontawesome/solid/pen-nib
      abstract: fontawesome/solid/list
      tip: fontawesome/solid/lightbulb
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: material/alien
      danger: fontawesome/solid/virus
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/link
  font:
    text: LXGW WenKai Screen GB Screen # Share Tech
    code: JetBrains Mono
  palette:
    scheme: default
    primary: brown
    accent: deep orange
  features:
    - content.code.annotate
    - content.code.copy
    # - navigation.instant # This will cause LaTeX render fail at the first try.
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    # - navigation.prune
  custom_dir: overrides

plugins:
  - minify
  # - statistics:
  #     words_per_minute: 200
  - glightbox
  - search:
      lang:
        - zh
        - en
      separator: '[\s\-\.]+'
  # - git-revision-date-localized:
  #     type: datetime
  #     timezone: Asia/Shanghai
  #     locale: zh
  #     enable_creation_date: true
  #     exclude:
  #       - index.md
  #       - coming.md
  #       - link.md
  #       - tech_accu/index.md
  #       - cour_note/index.md
  #       - pape_read/index.md
  #       - others/index.md
markdown_extensions:
  - toc:
      permalink: true # link for each title
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}} # enable Unicode link
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      # smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  # - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.tilde
  #- mdx_math

# KaTeX cdn from: [ https://www.bootcdn.cn/KaTeX/ ]

extra_css:
  - _css/extra.css
  - _css/flink.css
  # - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css
  # - https://cdn.jsdelivr.net/npm/cn-fontsource-lxgw-wen-kai-gb-screen@1.0.6/font.min.css
  ###- https://jsd.cdn.zzko.cn/npm/katex@0.16.4/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  # - https://cdn.staticfile.org/lxgw-wenkai-screen-webfont/1.6.0/lxgwwenkaiscreen.css


extra_javascript:
  - _js/extra.js
#  - _js/mathjax.js
  - _js/katex.js
  #- https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.js
  ###- https://jsd.cdn.zzko.cn/npm/katex@0.16.4/dist/katex.min.js
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#####
# #  - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/javascripts/extra.js  # extra的cdn
#   - javascripts/mathjax.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# # #####
nav:
  - 首页: 
    - index.md
    - my/11.md
  - First Echo: The First Echo of LOSS.md
  - 技术:
      - 函数空间与向量空间对比: my/量子力学.md
      - "for test": my/topic1.md
  - 标签: tag.md
