site_name: "Echoes of LOSS"
site_url: https://mydomain.org/mysite
theme:
  language: zh

  font:
    text: Roboto
    code: Roboto Mono
    
  name: material
  palette:
    #primary: light green
    #accent: deep orange

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
