authors:
  Wcowin:
    name: LOSS # Author name
    description: For test # Author description
    avatar:
    # https://s1.imagehub.cc/images/2024/02/02/91a767e93d1a344e44c69936464c583e.png         # Author avatar
